version: '3.7'
services:
  bidata-core:
    build:
      context: ./core
      target: base
      args:
        ENV: local
    image: bidata-core
    ports:
      - 9000:9000
    volumes:
      - ./core:/usr/src/app
    command: yarn dev

  bidata-auth:
    build:
      context: ./auth
      target: base
      args:
        ENV: local
    image: bidata-auth
    ports:
      - 9001:9000
    volumes:
      - ./auth:/usr/src/app
    command: yarn dev

  mongo-core:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: bidata
    volumes:
      - mongodb_data_container:/data/db

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_container:/var/lib/postgresql/data

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-core
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo-core
    ports:
      - 27080:8081

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bidata.local
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 54080:80


volumes:
  mongodb_data_container:
  postgres_data_container:
